# Generated by Django 5.0.4 on 2024-04-15 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('IDTipo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('IDProduto', models.AutoField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=200)),
                ('IDTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUDShop.tipo')),
            ],
        ),
    ]
