# Generated by Django 5.0.4 on 2024-04-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=200)),
                ('Tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
