# Generated by Django 5.0.4 on 2024-04-15 00:47

from django.db import migrations

def create_data(apps, schema_editor):
    Produto = apps.get_model('CRUDShop', 'Produto')
    Produto(descricao='dahora', preco=10.42, Tipo='foda').save()

class Migration(migrations.Migration):

    dependencies = [
        ('CRUDShop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
