# Generated by Django 5.0.3 on 2024-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(error_messages='ERRO: e-mail fornecido não é valido', max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=30)),
                ('enderecos', models.ManyToManyField(to='CRUDUsers.endereco')),
            ],
        ),
    ]
