# Generated by Django 5.0.3 on 2024-04-14 00:35

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('CRUDUsers', 'User')
    User(nome='Ninguém da Silva', email='ninguem@ninguem', senha='123mudar').save()


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDUsers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]